---
# tasks file for dbpatchmanager
- name: Update all packages - excluded database related ones
  yum:
    name: "*"
    state: latest
    exclude: pg*, postg*, python*, patroni*, barman*, pgbackrest*,couchbase*,postgis*
    skip_broken: yes
    update_cache: yes
    update_only: yes
  when: >-
    ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat
    Enterprise Linux'

- name: Mark important packages in order to prevent disaster - dba
  shell: apt-mark hold couchbase* postgresql*
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Update all packages on Debian and Ubuntu
  apt:
    name: "*"
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'