---
# tasks file for dbpatchmanager
- name: Stop service postgresql, if started
  service:
    name: patroni
    state: stopped
  when: >-
    ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat
    Enterprise Linux'
  ignore_erros: yes
- name: Sleep for 30 seconds
  wait_for:
    timeout: 30
  delegate_to: localhost
- name: Update all packages - excluded database related ones
  yum:
    name: "*"
    state: latest
    exclude: pg*, postg*, python*, patroni*, kernel*, barman*, pgbackrest*,couchbase*
    skip_broken: yes
    update_cache: yes
    update_only: yes
  when: >-
    ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat
    Enterprise Linux'
- name: Sleep for 30 seconds
  wait_for:
    timeout: 30
  delegate_to: localhost
- name: update database packages
  yum:
    name:
      - postgresql*
    state: latest
    update_only: yes
  when: >-
    ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat
    Enterprise Linux'

- name: Start service postgresql, if started
  service:
    name: patroni
    state: started
  when: >-
    ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat
    Enterprise Linux'
  ignore_erros: yes


- name: Prevent packages from being upgraded
  shell: apt-mark hold couchbase* linux* openjdk* init* grub* x11* libxcursor* pam* libx11* cloud-* busybox* libpam*
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Update all packages
  apt:
    name: "*"
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'